[[redirects]]
  from = "http://www.fingerprint.com"
  to = "https://fingerprint.com/"

[[redirects]]
  from = "/blog/wallpaper-id/"
  to = "/blog/how-android-wallpaper-images-threaten-privacy/"
  status = 301
  force = true

[[redirects]]
  from = "https://fpjs.io"
  to = "https://fingerprint.com/"
  force = true

[[redirects]]
  from = "http://fpjs.io"
  to = "https://fingerprint.com/"
  force = true

[[redirects]]
  from = "https://fingerprintjs.pro"
  to = "https://fingerprint.com/"
  force = true

[[redirects]]
  from = "http://fingerprintjs.pro"
  to = "https://fingerprint.com/"
  force = true

[[redirects]]
  from = "/open-source/"
  to = "/github/"
  force = true

[[redirects]]
  from = "/why-fpjs/"
  to = "/products/browser-fingerprinting/"
  force = true

[[redirects]]
  from = "/products/browser-fingerprinting/"
  to = "/products/device-identification/"
  status = 302
  force = true

[[redirects]]
  from = "/botd/"
  to = "/products/bot-detection/"
  force = true

[[redirects]]
  from = "/account-sharing/"
  to = "/products/account-sharing-prevention/"
  force = true

[[redirects]]
  from = "/blog/tag/account%20sharing/"
  to = "/blog/tag/account-sharing/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/account%20takeover/"
  to = "/blog/tag/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/account%20takeover/2/"
  to = "/blog/tag/account-takeover/2/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/anti-fraud%20technology/"
  to = "/blog/tag/anti-fraud-technology/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/bot%20attacks/"
  to = "/blog/tag/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/buy%20now%20pay%20later/"
  to = "/blog/tag/buy-now-pay-later/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/cryptocurrency%20fraud/"
  to = "/blog/tag/cryptocurrency-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/ecommerce%20fraud/"
  to = "/blog/tag/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/ecommerce%20fraud/2/"
  to = "/blog/tag/ecommerce-fraud/2/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/gaming%20fraud/"
  to = "/blog/tag/gaming-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/payment%20fraud/"
  to = "/blog/tag/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/payment%20fraud/2/"
  to = "/blog/tag/payment-fraud/2/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/alexey%20verkhovsky/"
  to = "/blog/author/alexey-verkhovsky/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/"
  to = "/blog/author/allan-macgregor/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/aniket%20bhattacharyea/"
  to = "/blog/author/aniket-bhattacharyea/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/courtney%20rogin/"
  to = "/blog/author/courtney-rogin/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/dan%20pinto/"
  to = "/blog/author/dan-pinto/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/frederik%20bussler/"
  to = "/blog/author/frederik-bussler/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/habdul%20hazeez/"
  to = "/blog/author/habdul-hazeez/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/james%20konik/"
  to = "/blog/author/james-konik/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josh%20alletto/"
  to = "/blog/author/josh-alletto/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josip%20miskovic/"
  to = "/blog/author/josip-miskovic/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/"
  to = "/blog/author/karl-hughes/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/konstantin%20darutkin/"
  to = "/blog/author/konstantin-darutkin/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/"
  to = "/blog/author/leon-yen/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/linda%20ikechukwu/"
  to = "/blog/author/linda-ikechukwu/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/lukonde%20mwila/"
  to = "/blog/author/lukonde-mwila/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20bajanik/"
  to = "/blog/author/martin-bajanik/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/"
  to = "/blog/author/martin-makarsky/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/piero%20borrelli/"
  to = "/blog/author/piero-borrelli/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/ravi%20bhanot/"
  to = "/blog/author/ravi-bhanot/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/"
  to = "/blog/author/savannah-copland/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/2/"
  to = "/blog/author/savannah-copland/2/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/"
  to = "/blog/author/sergey-mostsevenko/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/shahed%20nasser/"
  to = "/blog/author/shahed-nasser/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/alexey%20verkhovsky/android/"
  to = "/blog/author/alexey-verkhovsky/android/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/alexey%20verkhovsky/fingerprinting/"
  to = "/blog/author/alexey-verkhovsky/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/alexey%20verkhovsky/privacy/"
  to = "/blog/author/alexey-verkhovsky/privacy/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/alexey%20verkhovsky/vulnerability/"
  to = "/blog/author/alexey-verkhovsky/vulnerability/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/account%20takeover/"
  to = "/blog/author/allan-macgregor/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/bot%20attacks/"
  to = "/blog/author/allan-macgregor/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/ecommerce%20fraud/"
  to = "/blog/author/allan-macgregor/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/fingerprinting/"
  to = "/blog/author/allan-macgregor/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/payment%20fraud/"
  to = "/blog/author/allan-macgregor/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/allan%20macgregor/web/"
  to = "/blog/author/allan-macgregor/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/aniket%20bhattacharyea/fingerprinting/"
  to = "/blog/author/aniket-bhattacharyea/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/aniket%20bhattacharyea/web/"
  to = "/blog/author/aniket-bhattacharyea/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/courtney%20rogin/account%20takeover/"
  to = "/blog/author/courtney-rogin/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/courtney%20rogin/buy%20now%20pay%20later/"
  to = "/blog/author/courtney-rogin/buy-now-pay-later/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/courtney%20rogin/ecommerce%20fraud/"
  to = "/blog/author/courtney-rogin/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/courtney%20rogin/payment%20fraud/"
  to = "/blog/author/courtney-rogin/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/dan%20pinto/announcements/"
  to = "/blog/author/dan-pinto/announcements/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/frederik%20bussler/anti-fraud%20technology/"
  to = "/blog/author/frederik-bussler/anti-fraud-technology/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/frederik%20bussler/ecommerce%20fraud/"
  to = "/blog/author/frederik-bussler/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/habdul%20hazeez/fingerprinting/"
  to = "/blog/author/habdul-hazeez/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/james%20konik/fingerprinting/"
  to = "/blog/author/james-konik/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/james%20konik/js/"
  to = "/blog/author/james-konik/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/james%20konik/payment%20fraud/"
  to = "/blog/author/james-konik/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/james%20konik/web/"
  to = "/blog/author/james-konik/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josh%20alletto/bot%20attacks/"
  to = "/blog/author/josh-alletto/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josh%20alletto/fingerprinting/"
  to = "/blog/author/josh-alletto/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josh%20alletto/payment%20fraud/"
  to = "/blog/author/josh-alletto/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/josip%20miskovic/ecommerce%20fraud/"
  to = "/blog/author/josip-miskovic/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/account%20takeover/"
  to = "/blog/author/karl-hughes/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/bot%20attacks/"
  to = "/blog/author/karl-hughes/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/fingerprinting/"
  to = "/blog/author/karl-hughes/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/js/"
  to = "/blog/author/karl-hughes/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/payment%20fraud/"
  to = "/blog/author/karl-hughes/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/karl%20hughes/paywall/"
  to = "/blog/author/karl-hughes/paywall/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/konstantin%20darutkin/engineering/"
  to = "/blog/author/konstantin-darutkin/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/konstantin%20darutkin/fingerprinting/"
  to = "/blog/author/konstantin-darutkin/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/konstantin%20darutkin/js/"
  to = "/blog/author/konstantin-darutkin/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/account%20takeover/"
  to = "/blog/author/leon-yen/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/bot%20attacks/"
  to = "/blog/author/leon-yen/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/ecommerce%20fraud/"
  to = "/blog/author/leon-yen/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/fingerprinting/"
  to = "/blog/author/leon-yen/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/payment%20fraud/"
  to = "/blog/author/leon-yen/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/leon%20yen/privacy/"
  to = "/blog/author/leon-yen/privacy/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/linda%20ikechukwu/account%20sharing/"
  to = "/blog/author/linda-ikechukwu/account-sharing/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/linda%20ikechukwu/account%20takeover/"
  to = "/blog/author/linda-ikechukwu/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/linda%20ikechukwu/fingerprinting/"
  to = "/blog/author/linda-ikechukwu/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/linda%20ikechukwu/web/"
  to = "/blog/author/linda-ikechukwu/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/lukonde%20mwila/fingerprinting/"
  to = "/blog/author/lukonde-mwila/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/lukonde%20mwila/js/"
  to = "/blog/author/lukonde-mwila/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/lukonde%20mwila/paywall/"
  to = "/blog/author/lukonde-mwila/paywall/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20bajanik/engineering/"
  to = "/blog/author/martin-bajanik/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20bajanik/leak/"
  to = "/blog/author/martin-bajanik/leak/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/announcements/"
  to = "/blog/author/martin-makarsky/announcements/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/ecommerce%20fraud/"
  to = "/blog/author/martin-makarsky/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/fingerprinting/"
  to = "/blog/author/martin-makarsky/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/payment%20fraud/"
  to = "/blog/author/martin-makarsky/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/martin%20makarsky/web/"
  to = "/blog/author/martin-makarsky/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/piero%20borrelli/engineering/"
  to = "/blog/author/piero-borrelli/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/ravi%20bhanot/announcements/"
  to = "/blog/author/ravi-bhanot/announcements/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/ravi%20bhanot/engineering/"
  to = "/blog/author/ravi-bhanot/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/account%20sharing/"
  to = "/blog/author/savannah-copland/account-sharing/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/account%20takeover/"
  to = "/blog/author/savannah-copland/account-takeover/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/android/"
  to = "/blog/author/savannah-copland/android/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/announcements/"
  to = "/blog/author/savannah-copland/announcements/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/anti-fraud%20technology/"
  to = "/blog/author/savannah-copland/anti-fraud-technology/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/bot%20attacks/"
  to = "/blog/author/savannah-copland/bot-attacks/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/cryptocurrency%20fraud/"
  to = "/blog/author/savannah-copland/cryptocurrency-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/ecommerce%20fraud/"
  to = "/blog/author/savannah-copland/ecommerce-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/engineering/"
  to = "/blog/author/savannah-copland/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/fingerprinting/"
  to = "/blog/author/savannah-copland/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/gambling/"
  to = "/blog/author/savannah-copland/gambling/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/gaming%20fraud/"
  to = "/blog/author/savannah-copland/gaming-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/java/"
  to = "/blog/author/savannah-copland/java/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/js/"
  to = "/blog/author/savannah-copland/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/payment%20fraud/"
  to = "/blog/author/savannah-copland/payment-fraud/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/paywall/"
  to = "/blog/author/savannah-copland/paywall/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/savannah%20copland/web/"
  to = "/blog/author/savannah-copland/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/apple/"
  to = "/blog/author/sergey-mostsevenko/apple/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/engineering/"
  to = "/blog/author/sergey-mostsevenko/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/fingerprinting/"
  to = "/blog/author/sergey-mostsevenko/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/ios/"
  to = "/blog/author/sergey-mostsevenko/ios/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/js/"
  to = "/blog/author/sergey-mostsevenko/js/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/leak/"
  to = "/blog/author/sergey-mostsevenko/leak/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/privacy/"
  to = "/blog/author/sergey-mostsevenko/privacy/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/vulnerability/"
  to = "/blog/author/sergey-mostsevenko/vulnerability/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/sergey%20mostsevenko/web/"
  to = "/blog/author/sergey-mostsevenko/web/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/shahed%20nasser/engineering/"
  to = "/blog/author/shahed-nasser/engineering/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/shahed%20nasser/fingerprinting/"
  to = "/blog/author/shahed-nasser/fingerprinting/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/author/shahed%20nasser/paywall/"
  to = "/blog/author/shahed-nasser/paywall/"
  status = 301
  force = true

[context.branch-deploy]
  command = "yarn noIndexBuild"

[[plugins]]
  package = "@netlify/plugin-gatsby"
