backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/account-sharing-test-page.md'
        label: 'Account sharing test layout'
        name: 'account-sharing-page'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'account-sharing-page' }
          - { label: Title, name: title, widget: string }
          - {
              label: Image block 1,
              name: block1,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Subheader, name: subheader, widget: string },
                  { label: Bullets, name: bullets, widget: list },
                  { label: Is image after text?, name: isImageAfterText, widget: boolean },
                  { label: CTA text, name: ctaText, widget: string },
                  { label: CTA url, name: ctaUrl, widget: string },
                  { label: Is CTA a primary button?, name: isCtaButton, widget: boolean },
                ],
            }
          - {
              label: Image block 2,
              name: block2,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Subheader, name: subheader, widget: string },
                  { label: Bullets, name: bullets, widget: list },
                  { label: Is image after text, name: isImageAfterText, widget: boolean },
                  { label: CTA text, name: ctaText, widget: string },
                  { label: CTA url, name: ctaUrl, widget: string },
                  { label: Is CTA a primary button, name: isCtaButton, widget: boolean },
                ],
            }
          - {
              label: Inline CTA,
              name: inlineCta,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  { label: Button text, name: buttonText, widget: string },
                  { label: Button href, name: buttonHref, widget: string },
                ],
            }
