backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: 'index'
    label: 'Root pages'
    folder: 'content/index'
    create: false
    delete: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'static-page-content' }
      - {
          label: Metadata,
          name: metadata,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: string },
              { label: URL, name: url, widget: string },
              { label: Image, name: image, widget: image },
            ],
        }
      - { label: Invert content order, name: invertContent, widget: boolean, default: false }
      - {
          label: Hero,
          name: hero,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: string },
              { label: CTA Text, name: ctaText, widget: string },
              { label: CTA Href, name: ctaHref, widget: string },
              { label: open CTA link in new tab, name: openCtaNewTab, widget: boolean, default: false },
            ],
        }
      - {
          label: CardSection,
          name: cardSection,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Subtitle, name: subtitle, widget: string, required: false },
              {
                label: Cards,
                name: cards,
                widget: list,
                fields:
                  [
                    { label: Icon, name: icon, widget: image, required: false },
                    { label: Icon Alt, name: iconAlt, widget: string, required: false },
                    { label: Icon Title, name: iconTitle, widget: string, required: false },
                    { label: Title, name: title, widget: string },
                    { label: Content, name: markdown__Content, widget: markdown },
                  ],
              },
            ],
        }
      - {
          label: Blocks,
          name: blocks,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Image Alt, name: imageAlt, widget: string, required: false },
              { label: Image Title, name: imageTitle, widget: string, required: false },
              { label: Subheader, name: subheader, widget: string },
              { label: Content, name: markdown__Content, widget: markdown },
              { label: Is image after text, name: isImageAfterText, widget: boolean },
              { label: CTA text, name: ctaText, widget: string },
              { label: CTA url, name: ctaUrl, widget: string },
              { label: Is CTA a primary button, name: isCtaButton, widget: boolean },
            ],
        }
      - {
          label: Inline CTA,
          name: inlineCta,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Subtitle, name: markdown__Subtitle, widget: markdown },
              { label: Button text, name: buttonText, widget: string },
              { label: Button href, name: buttonHref, widget: string },
            ],
        }
  - name: 'blog'
    label: 'Blog'
    folder: content/blog
    create: true
    delete: true
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'long-form-content' }
      - {
          label: Metadata,
          name: metadata,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string, default: 'Default Title' },
              { label: Description, name: description, widget: string },
              { label: URL, name: url, widget: string },
              { label: Image, name: image, widget: image },
              { label: Image Alt, name: imageAlt, widget: string, required: false },
              { label: Image Title, name: imageTitle, widget: string, required: false },
            ],
        }
      - { label: Featured, name: featured, widget: boolean }
      - { label: Publish date, name: publishDate, widget: datetime }
      - { label: Title, name: title, widget: string, default: 'Default Title' }
      - name: tags
        label: Tags
        widget: relation
        collection: 'tag'
        searchFields: ['name']
        valueField: 'name'
        displayFields: ['name']
        multiple: true
        default: ['fingerprinting']
      - name: authors
        label: Authors
        widget: relation
        collection: 'author'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']
        multiple: true
        default: ['Savannah Copland']
      - { label: Body, name: body, widget: markdown }
  - name: 'tag'
    label: 'Tag'
    folder: content/tag
    create: true
    fields:
      - {
          label: 'Name',
          name: 'name',
          widget: string,
          pattern: ['[a-z]+[a-z\-]*', 'Must be all lowercase words, optionally separated by a "-".'],
        }
  - name: 'author'
    label: 'Author'
    folder: content/author
    create: true
    fields: [
        { label: Name, name: title, widget: string }, # The filename comes from title
        { label: Role, name: role, widget: string },
        { label: Photo, name: photo, widget: image },
        { label: Bio, name: markdown__bio, widget: markdown, required: false },
      ]
  - name: 'caseStudy'
    label: 'Case Study'
    folder: 'content/case-study'
    create: true
    delete: true
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'case-study-content' }
      - { label: Publish date, name: publishDate, widget: datetime }
      - { label: Title, name: title, widget: string }
      - {
          label: Metadata,
          name: metadata,
          widget: object,
          fields:
            [
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: string },
              { label: URL, name: url, widget: string },
            ],
        }
      - {
          label: Header,
          name: header,
          widget: object,
          fields:
            [
              { label: Label, name: subLabel, widget: string, default: 'Case Study' },
              { label: Title, name: subTitle, widget: string },
              { label: Description, name: markdown__Content, widget: markdown },
              {
                label: PDF,
                name: pdf,
                widget: file,
                media_folder: '/static/pdf/case-study',
                public_folder: '/pdf/case-study',
              },
            ],
        }
      - {
          label: Summary,
          name: summary,
          widget: object,
          fields:
            [
              {
                label: Results,
                name: results,
                widget: list,
                fields:
                  [
                    {
                      label: Icon,
                      name: icon,
                      widget: image,
                      media_folder: '/static/img/uploads',
                      public_folder: '/img/uploads',
                    },
                    { label: Icon Alt, name: iconAlt, widget: string, required: false },
                    { label: Icon Title, name: iconTitle, widget: string, required: false },
                    { label: Title, name: title, widget: string },
                    { label: Content, name: markdown__Content, widget: markdown },
                  ],
              },
              {
                label: Overview,
                name: overviewSection,
                widget: object,
                fields:
                  [
                    { label: Description, name: description, widget: string },
                    {
                      label: Bullets,
                      name: bullets,
                      widget: list,
                      fields:
                        [
                          { label: Value, name: value, widget: string },
                          { label: Description, name: description, widget: string },
                        ],
                    },
                  ],
              },
            ],
        }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Footer,
          name: footer,
          widget: object,
          fields:
            [
              { label: Cta Title, name: ctaTitle, widget: string, default: 'Get in Touch' },
              {
                label: Cta Subtitle,
                name: ctaSubtitle,
                widget: string,
                default: 'Learn how FingerprintJS Pro can help your business build a custom solution to prevent online fraud.',
              },
            ],
        }
